### PR TITLE
Add white PHPBenelux elePHPant

### PR DESCRIPTION
**Pull request by cookieguru**

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Looks like this came from an old branch - any chance you could take a look to rebase it?

**Comment by cookieguru** [comment]
Done!

**Comment by ramondelafuente** [comment]
Oh yeah, there was some major re-shuffling done to get a more consistent codebase (and more in line with Symfony Flex). It looks like the commit now adds two files, which where moved somewhere else in the meantime.

Breed is now here `elewant/src/Elewant/Herding/DomainModel/Breed/Breed.php`
And the translations are here `elewant/src/Elewant/Webapp/Application/Resources/translations/herd.en.yml`

**Comment by ramondelafuente** [comment]
Sorry about that - we're always super happy with the new elephpant contributions!

**Comment by cookieguru** [comment]
My bad, I should've checked the diff again after rebasing; good to go now!

**Pull request merged**
