### PR TITLE
Add XDebug to docker

### PR DESCRIPTION
**Pull request by ramondelafuente**
Add XDebug to docker. For obvious reasons.

This can do with an enable/disable mechanism later.

### CODE REVIEW

**Comment by cookieguru** [comment]
I think https://jtreminio.com/blog/developing-at-full-speed-with-xdebug is a prime candidate for the future enable/disable mechanism!

**Comment by ramondelafuente** [comment]
@cookieguru Implemented (mostly) what the article does. I kept "PHPSTORM" as the xdebug cookie though. I also implemented the "enable" for xdebug through an environment variable, so test runs don't slow down, but you still have the option to run cli with xdebug enabled.

**Comment by edwinkortman** [comment]
That's really useful @cookieguru! Be right back while implementing this for other projects. ;-)

**Review by edwinkortman — APPROVED** [review]

**Comment by cookieguru** [comment]
All credit goes to @jtreminio, I'm just the messenger 😉

**Pull request merged**
