### PR TITLE
Removed unneeded large SunshinePHP breed (none ever created), and cha…

### PR DESCRIPTION
**Pull request by adamculp**
Removed unneeded large SunshinePHP breed (none ever created), and changed the title of the original to reflect Zend as the sponsor to be consistent with the Nexmo branded breed. Added name Sonny.

### CODE REVIEW

**Comment by cookieguru** [comment]
Would be a good idea to add [migrations](https://github.com/f500/elewant/tree/develop/src/Tooling/DoctrineMigrations) to remove any orphan rows.

Also, I'm curious about the addition of Sonny to the name.  Skimming over the list most of them just use the "breed name" instead of the "given name".  I suppose this saves space but I'm not sure if there is any other rationale for doing it one way or another; there's discussion on #109

**Comment by adamculp** [comment]
Not sure migrations are needed in this case. There are only 2 large yellow elephpants, and they should both be the Nexmo variety. No Zend variety was created in large format.

I think the "names" should not be in the CONSTANTS, unless it makes sense. That is why I added "Sonny" in the translation names versus CONSTANTS. I also added "Zend" in the text rather than renaming the CONSTANT. This will eliminate the need for a migration to fix any orphans.

**Comment by cookieguru** [comment]
There are users that already have the Large Sonny Jr. on their wanted list ([example](https://elewant.com/shepherd/admire/tdutrion#herd_desires)).  I hope nobody already said they own one, but either way, the migrations would look like:
```sql
DELETE FROM desired_breed WHERE breed = 'YELLOW_SUNSHINEPHP_LARGE';
DELETE FROM herd WHERE breed = 'YELLOW_SUNSHINEPHP_LARGE';
```

I understand your change was only for the display names, but what I was mentioning is that the UI generally does not show the names; e.g. there is no "Chilli" or "MurPHPy" and instead they display solely as "Zend Red" and "AmsterdamPHP".

**Comment by adamculp** [comment]
Would you like me to remove "Sonny" while I create the migrations?

**Comment by cookieguru** [comment]
I'd defer to @ramondelafuente on that one

**Comment by ramondelafuente** [comment]
Those migrations are not required, as this is event-sourced and those tables are filled by running all the events through a _projection_.
But: it does mean we have an interesting case here, where replaying the old events might cause problems. Since the string `YELLOW_SUNSHINEPHP_LARGE` is data in existing `ElePHPantWasDesiredByHerd` events.

This, by the way,  is exactly why this project is event-sourced in the first place. To gain some practical experience in real-world problems like this, and ways to deal with them. So the question is now, what happens when a breed that used to exist goes extinct?

One way would be to remove all the events that refer to that breed from the event store. But that would be considered cheating, since the event store should be immutable. 

We could also add tests that try to _adopt_, _abandon_  and _desire_  a non-existent breed, and then adjust the `Herd` aggregate to effectively ignore those events (do not add them to the herd). That way, the historical events still exist, but nothing happens when they occur.

**Comment by ramondelafuente** [comment]
Thank you by the way, @adamculp for your PR!

**Comment by ramondelafuente** [comment]
I decided that an event store isn't actually "immutable" like history, but more like a history _book_. There are  plenty of examples of events that happened, but where then erased from the history books.

Maybe not such a good example to follow but hey, I'll take practical solutions over theoretical purity any day.

So in that light, these events should never have existed in the first place and are hereby purged from existance.

See #234 for the code required to handle a non-existant Breed in the domain model.

**Pull request merged**
