### PR TITLE
 Add large PHPCON Japan elePHPant 

### PR DESCRIPTION
**Pull request by cookieguru**
https://twitter.com/phpcon/status/1199301083719323648

### CODE REVIEW

**Comment by cookieguru** [comment]
Where'd the develop branch go?

**Comment by ramondelafuente** [comment]
Whoops - I'm going too fast it seems.
I've implemented github actions for deployment to staging and production.
To staging on merge to master, and to production on creation of a new tag.

It makes little sense to have a develop branch, we can just work from master. So I changed the default branch and removed develop - with no notice whatsoever - my bad!

**Comment by ramondelafuente** [comment]
I also updated symfony and some additional dependencies.

More steps will include improved logging and monitoring - this project has not been loved as it deserves to be :)

**Comment by ramondelafuente** [comment]
Can you make sure this branch only contains commits required for the change?

**Comment by cookieguru** [comment]
Fixed.  Tried to do it from my phone and failed

**Comment by ramondelafuente** [comment]
Okay. Let's se how much happyness this automation is going to bring (me :) )

**Comment by ramondelafuente** [comment]
Screenshot 2019-11-27 at 10 43 54

W00tW00t!

**Pull request merged**
