### PR TITLE
show herd as icons on front page

### LINKED ISSUE #100: Add a small colored elephpant to the "newest herd" list
In the "newest herd" list there are breed names, but it would be nicer to see an actual colored elephpant. All ElePHPants in the herd could be shown in a grid instead of the name in text.

### PR DESCRIPTION
**Pull request by Gwendolyn68**
schermafbeelding 2017-10-14 om 22 07 32

Fixes #100

### CODE REVIEW

**Comment by ramondelafuente** [comment]
I've changed the way the views work when looping over breeds, so there are conflicts now. I can help resolve the conflicts if you get stuck (let me know if you don't know how to get started).

But before you do, I'm not sure this view is an improvement over the current list of names. It has nothing to do with your work, your change is exactly what the open issue #100  describes. But now that it's there, It looks a bit messy...

**Comment by jaspernbrouwer** [comment]
I have to agree with Ramon, it does look a bit messy. But I like the idea of showing icons rather than labels!

Maybe the icons can be smaller, like between 10px &times; 10px and 20px &times; 20px. Then display max 8 or 10 of them on a single line. Maybe the could align bottom-right on the big circle (with the picture in it) and move to the left, so it creates a line going through the big circle ending just right of that circle. I hope this makes sense! 😄

**Review by jaspernbrouwer — CHANGES_REQUESTED** [review]
I have to agree with Ramon, it does look a bit messy. But I like the idea of showing icons rather than labels!

Maybe the icons can be smaller, like between 10px &times; 10px and 20px &times; 20px. Then display max 8 or 10 of them on a single line. Maybe they could align bottom-right on the big circle (with the picture in it) and move to the left, so it creates a line going through the big circle ending just right of that circle. I hope this makes sense! 😄

**Comment by ramondelafuente** [comment]
It seems after removing the limit on the list and just showing the entire thing, it doesn't look bad at all. So the current decision is that we leave this as-is for now.

@Gwendolyn68  Thank you for the effort though;  I'll gladly help you out with a different issue in the list if you want to keep working on the project!

**Pull request closed without merging**
