### PR TITLE
Feature/updrade to symfony4 with flex

### PR DESCRIPTION
**Pull request by ramondelafuente**
This was... interesting.

In it's curent state, this PR would upgrade the project and it _should_ work as-is for vagrant and docker.

BUT: We still need to install a new production server (or upgrade MariaDB to 10.2) and migrate all the existing events.

### CODE REVIEW

**Comment by edwinkortman** [comment]
It looks like the `mariadb` addon is missing in Travis causing the tests to fail.

```
addons:
	mariadb: '10.2'
```

I am also a tad bit confused by the "BUT". Why is it a new server or upgrading MariaDB? Upgrading seems less invasive.

**Comment by ramondelafuente** [comment]
The checks fail because the tests are in limbo - the docker setup and vagrant setup and test setup are all different, and it's just a pain trying to support everything.
I'm going to change the tests to run through Docker, and I'm strongly in favor of removing vagrant completely... We *could* look at adding it later when we have a stable situation.

**Comment by jaspernbrouwer** [comment]
I have some issues "Getting started with Docker":

---

`bin/setup.sh` displays:

```
 [KO]
Script cache:clear returned with error code 255
!!  
!!  Fatal error: Uncaught Symfony\Component\Dotenv\Exception\FormatException: A value containing spaces must be surrounded by quotes in "/opt/project/bin/../.env" at line 26.
!!  ...=[insert value here]\n#TWITTER_CLIENT_ID=...
!!                        ^ line 26 offset 1259 in /opt/project/vendor/symfony/dotenv/Dotenv.php:400
!!  Stack trace:
!!  #0 /opt/project/vendor/symfony/dotenv/Dotenv.php(255): Symfony\Component\Dotenv\Dotenv->createFormatException('A value contain...')
!!  #1 /opt/project/vendor/symfony/dotenv/Dotenv.php(128): Symfony\Component\Dotenv\Dotenv->lexValue()
!!  #2 /opt/project/vendor/symfony/dotenv/Dotenv.php(57): Symfony\Component\Dotenv\Dotenv->parse('# This file is ...', '/opt/project/bi...')
!!  #3 /opt/project/bin/console(22): Symfony\Component\Dotenv\Dotenv->load('/opt/project/bi...')
!!  #4 {main}
!!    thrown in /opt/project/vendor/symfony/dotenv/Dotenv.php on line 400
!!
```

This is resolved by replacing `[insert value here]` with the real value. Maybe put this in the readme?

---

Next `bin/setup.sh` displays:

```
In MariaDbEventStore.php line 765:

  Error 42S02. Maybe the event streams table is not setup?
  Error-Info: Table 'elewant.event_streams' doesn't exist

event-store:event-stream:create [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

Not sure what to do here...

---

Finally I run `docker-compose up -d`, visit `http://localhost.elewant.com/` and see:

```
File not found. 
```

**Comment by jaspernbrouwer** [comment]
I've added some commits to add a new migration version for the new even-stream db structure, and commented out the old one. This solves the `Table 'elewant.event_streams' doesn't exist` issue.

The `File not found.` issue can be solved by (re)building the Docker images.

This PR still **does not** migrate the old event-stream to the new event-stream!

**Pull request merged**
