### PR TITLE
Add Red PHPCon Poland elePHPant

### PR DESCRIPTION
**Pull request by cookieguru**
Via @MarkBaker: The Red PHPCon Poland is official, but the purple one is not

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Something seems off - the PR references `RED_PHPCON_JAPAN_REGULAR: "PHPCON Poland"`

**Comment by cookieguru** [comment]
Now  you have some insight in to my development strategy: copy and paste something else 😁

Fixed

**Comment by cookieguru** [comment]
Added some new CSS because why not

Screenshot of PHPCon Poland elePHPant icon in a herd's listing page

**Comment by ramondelafuente** [comment]
Love it :D

**Pull request merged**
