### PR TITLE
Add a first naive implementation of docker for development

### PR DESCRIPTION
**Pull request by ramondelafuente**
This change makes it possible to use Docker for development, on the URL `localhost.elewant.com`.

The URL was chosen because A: Docker connects though a local port 127.0.0.1:80 and B: it's in the global DNS and therefore doesn't require a hostfile entry.

Feel free to test this setup by following the docs.

### CODE REVIEW

**Comment by cookieguru** [comment]
@ramondelafuente This worked fairly well.

I am on a Windows host, so I couldn't run `setup.sh` directly.  The first line is straightforward, and the rest are pretty much copy/paste/pray.

The composer install step produced output that scrolled by as fast as level 42 of Tetris.  Because of this I didn't really pay attention to the output nor did I check to see if the migrations and npm tasks succeeded.  When I started up the containers they had not, as the database was completely empty and the CSS was missing.  However _after_ the DB had started I ran the migrations command without issue.
The last two commands proved the most challenging; running them resulted in:
```plain
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```
[One of my favorite books](https://raw.githubusercontent.com/thepracticaldev/orly-full-res/master/googlingtheerrormessage-big.png) didn't have the answer.  However I already had npm installed on the host machine so running those two commands without Docker was trivial.

I'm new to Docker so I don't want to make too many assumptions, but my theory is that the migrations failed because they tried to run on a host that was not yet up.

**Comment by ramondelafuente** [comment]
Okay, we've had an instance of the same here in the office so I know what caused it:

The parameters.yml file is copied from a dist version, but it's only copied once (so if the file already exists, it is not copied). Since we wanted to support both Vagrant and Docker for now - the parameters are slightly different. In this case, if you where already working with Vagrant, the parameters file has the wrong host for DB connection and the Migrations step in docker fails...

The last two commands are used to install the NPM dependencies and run grunt - I personally do not have NPM on my host machine and when I did, it failed quite often due to version issues. So I tried to find docker images that could run these commands, I'm quite disappointed that that doesn't "just work"
*grin*

Maybe we could experiment with some other images to see which ones work on windows? I basically just select something from docker hub that looks supported and stable...

**Comment by cookieguru** [comment]
Though I previously had tried the Vagrant route, I couldn't get it to do its thing and backed out everything that it had set up.  So this was a fresh install with Docker (and fresh clone to boot) and thus there was no `parameters.yml`.

FWIW I'm running npm 5.6.0  and grunt-cli v1.2.0.

**Comment by ramondelafuente** [comment]
Owww too bad - I though I'd found it. I'll keep looking.

**Pull request merged**
